version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: movie-rater-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: movie-rater-db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
